taskkill /f /im "Razer Central.exe"
taskkill /f /im "Razer Synapse 3.exe"
taskkill /f /im "Razer Synapse Service Process.exe"
taskkill /f /im "Razer Synapse Service.exe"
taskkill /f /im "RazerCentralService.exe"
taskkill /f /im "GameManagerService.exe"
::taskkill /f /im "steamwebhelper.exe"
::taskkill /f /im "steamwebhelper.exe"
::taskkill /f /im "steamwebhelper.exe"
exit